server.port=8080
spring.application.name=customer-wishlist-service

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

logging.level.org.springframework=INFO
logging.level.org.springframework.data.mongodb.core=DEBUG