server.port=8080
spring.application.name=customer-wishlist-service

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=${MONGODB_DATABASE:wishlist-db}

logging.level.org.springframework=INFO
logging.level.org.springframework.data.mongodb.core=DEBUG